import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter()
  const handleLogin = () => {
    let authorizeRedirect = 'https://accounts.spotify.com/authorize'
    authorizeRedirect += '?response_type=token'
    authorizeRedirect +=
      '&client_id=' + encodeURIComponent(process.env.NEXT_PUBLIC_CLIENT_ID)
    authorizeRedirect +=
      '&scope=' + encodeURIComponent('user-top-read playlist-read-private')
    authorizeRedirect +=
      '&redirect_uri=' + encodeURIComponent('http://localhost:3000/callback')
    router.push(authorizeRedirect)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <button onClick={() => handleLogin()}>Login To Spotify</button>
      </main>
    </div>
  )
}
